preprocessing:
  - GeminiMarkdownProcessor

chunking:
  - name: FixedParagraphChunker
    chunk_sizes: [1, 2, 3]
    overlaps: [0, 1]

  - name: FixedCharacterChunker
    chunk_sizes: [200, 300, 500]
    overlaps: [0, 50]