documents:
  - "documents/PO.pdf"
  - "documents/MHB.pdf"
  - "documents/POges.pdf"

offline_config:
  embedding_model: "storage/models/jina-embeddings"
  chunking_params:
    chunk_size: 1
    overlap: 0

online_config:
  top_k: 9
  top_n: 3
  generation_model: "Qwen/Qwen3.5-2B"

offline_pipeline:
  preprocessors:
    - "GeminiMarkdownProcessor"
    - "DirectLLMProcessor"
  chunker: "FixedParagraphChunker"
  index_builder: "FaissIndexBuilder"

online_pipeline:
  query_processor: "NoProcessingProcessor"
  retriever: "FaissRetriever"
  reranker: "JinaReranker"
  generator: "HuggingfaceGenerator"