documents:
  - "documents/PO.pdf"
  - "documents/MHB.pdf"
  - "documents/POges.pdf"

offline_config:
  embedding_model: "jinaai/jina-embeddings-v5-text-nano"
  chunking_params:
    {"chunk_size": 500, "overlap": 50}

online_config:
  top_k: 36
  top_n: 12
  reranking_score_threshold: 0.00
  generation_model: "Qwen/Qwen3.5-2B"

offline_pipeline:
  preprocessors:
    - "GeminiMarkdownProcessor"
    - "DirectLLMProcessor"
  chunker: "FixedCharacterChunker"
  index_builder: "FaissIndexBuilder"

online_pipeline:
  query_processor: "CoTQueryProcessor"
  retriever: "FaissRetriever"
  reranker: "JinaReranker"
  generator: "HuggingfaceGenerator"