documents:
  - "documents/PO.pdf"
  - "documents/MHB.pdf"
  - "documents/POges.pdf"

offline_config:
  embedding_model: "jinaai/jina-embeddings-v5-text-nano"
  chunking_params:
    {}

online_config:
  top_k: 20
  top_n: 5
  generation_model: "Qwen/Qwen3.5-2B"

offline_pipeline:
  preprocessors:
    - "GeminiMarkdownProcessor"
  chunker: "SplitTableParagraphChunker"
  index_builder: "FaissIndexBuilder"

online_pipeline:
  query_processor: "NoProcessingProcessor"
  retriever: "FaissRetriever"
  reranker: "JinaReranker"
  generator: "HuggingfaceGenerator"